fallback = ""

[matching]
calibre-gui = ""
chromium-browser = ""
DevToys = ""
jetbrains-datagrip = ""
jetbrains-pycharm = ""
KeePassXC = ""
"spotify" = ""
"/Transmission/" = ""
"virt-manager" = ""
