packages = [
  "alacritty", 
  "bat",
  "cargo",
  "delta",
  "git",
  "google-chrome",
  "gpg",
  "imv",
  "lazygit",
  "lsd",
  "mako",
  "nvim",
  "podman",
  "spotify",
  "ssh",
  "starship",
  "sway",
  "swaylock",
  "sworkstyle",
  "uwsm",
  "waybar",
  "wofi",
  "xdg",
  "zsh",
]

[files]
"sway/monitor.jchacking-pc" = "~/.config/sway/monitor"

[variables]
hardware.isGraphicNvidia = true
